deploy:
  image:
    name: docker.k8s.local/jdwheels/bitnami-kubectl:1.22
    entrypoint: [""]
  script:
    - kubectl config use-context mockexchange/mockexchange-agent:primary
    - kubectl get pods -n mockexchange
