name: GitHub Actions Demo
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - run: npm test
      - run: npm run build --if-present
      - name: 'Upload dist'
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 1
  deploy:
    needs:
      - build
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist
      - run: |
          ls ${{ github.workspace }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
#          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.AWS_REGION }}
      - name: Copy files to the test website with the AWS CLI
        env:
          UI_BUCKET: ${{ secrets.UI_BUCKET }}
        run: |
#          aws s3 ls $UI_BUCKET
          aws s3 sync --delete . $UI_BUCKET
      - name: Invalidate the cache
        env:
          UI_DISTRIBUTION: ${{ secrets.UI_DISTRIBUTION }}
        run: |
          aws cloudfront create-invalidation --distribution-id $UI_DISTRIBUTION --paths "/*"

#          aws s3 sync --delete . $UI_BUCKET
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "🍏 This job's status is ${{ job.status }}."
